AWSTemplateFormatVersion: "2010-09-09"
Resources:
  ExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      MaxSessionDuration: 8400
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - "lambda.amazonaws.com"  # required for EKS clusters with Public Endpoint disabled
                - "resources.cloudformation.amazonaws.com"
            Action: sts:AssumeRole
      Path: "/"
      Policies:
        - PolicyName: ResourceTypePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - "lambda:UpdateFunctionConfiguration" # required for EKS clusters with Public Endpoint disabled
                  - "lambda:GetFunctionConfiguration" # required for EKS clusters with Public Endpoint disabled
                  - "lambda:DeleteFunction"  # required for EKS clusters with Public Endpoint disabled
                  - "lambda:GetFunction"  # required for EKS clusters with Public Endpoint disabled
                  - "lambda:InvokeFunction"  # required for EKS clusters with Public Endpoint disabled
                  - "lambda:CreateFunction"  # required for EKS clusters with Public Endpoint disabled
                  - "lambda:UpdateFunctionCode"  # required for EKS clusters with Public Endpoint disabled
                  - "logs:CreateLogGroup"  # required if this role is also used for Resource type logging
                  - "logs:CreateLogStream"  # required if this role is also used for Resource type logging
                  - "logs:DescribeLogGroups"  # required if this role is also used for Resource type logging
                  - "logs:DescribeLogStreams"  # required if this role is also used for Resource type logging
                  - "logs:PutLogEvents"  # required if this role is also used for Resource type logging
                  - "cloudwatch:ListMetrics"  # required if this role is also used for Resource type logging
                  - "cloudwatch:PutMetricData"  # required if this role is also used for Resource type logging
                Resource: "*"
Outputs:
  ExecutionRoleArn:
    Value: !GetAtt ExecutionRole.Arn
