AWSTemplateFormatVersion: "2010-09-09"
Description: "registers the Noverant::Kubernetes::Resource and Noverant::Kubernetes::Apply resource types"
Parameters:
  ExecutionRoleArn:
    Type: String
    Description: IAM role ARN for the resource types
Resources:
  ApplyResourceVersion:
    Type: AWS::CloudFormation::ResourceVersion
    Properties:
      TypeName: Noverant::Kubernetes::Resource
      LoggingConfig:
        LogGroupName: cloudformation/registry/noverant-kubernetes-resource
        LogRoleArn: !Ref ExecutionRoleArn
      SchemaHandlerPackage: s3://nvt-cfn-extensions/cfn-kubernetes-resource-provider/noverant_kubernetes_apply.zip
      ExecutionRoleArn: !Ref ExecutionRoleArn
  GetResourceVersion:
    Type: AWS::CloudFormation::ResourceVersion
    Properties:
      TypeName: Noverant::Kubernetes::Get
      LoggingConfig:
        LogGroupName: cloudformation/registry/noverant-kubernetes-resource
        LogRoleArn: !Ref ExecutionRoleArn
      SchemaHandlerPackage: s3://nvt-cfn-extensions/cfn-kubernetes-resource-provider/noverant_kubernetes_get.zip
      ExecutionRoleArn: !Ref ExecutionRoleArn
  ApplyResourceDefaultVersion:
    Type: AWS::CloudFormation::ResourceDefaultVersion
    Properties:
      TypeVersionArn: !Ref ApplyResourceVersion
  GetResourceDefaultVersion:
    Type: AWS::CloudFormation::ResourceDefaultVersion
    Properties:
      TypeVersionArn: !Ref GetResourceVersion
Footer
© 2023 GitHub, Inc.
Footer navigation

    Terms
    Privacy
    Security
    Status
    Docs
    Contact GitHub
    Pricing
    API
    Training
    Blog
    About

