AWSTemplateFormatVersion: "2010-09-09"
Description: "registers the AWSQS::Kubernetes::Resource - Which is Deprecated."
Parameters:
  ExecutionRoleArn:
    Type: String
    Description: IAM role ARN for the resource types
Resources:
  KubernetesResourceVersion:
    Type: AWS::CloudFormation::ResourceVersion
    Properties:
      TypeName: AWSQS::Kubernetes::Resource
      LoggingConfig:
        LogGroupName: cloudformation/registry/awsqs-kubernetes-resource
        LogRoleArn: !Ref ExecutionRoleArn
      SchemaHandlerPackage: s3://aws-quickstart/quickstart-kubernetes-resource-provider/awsqs_kubernetes_resource.zip
      ExecutionRoleArn: !Ref ExecutionRoleArn
  KubernetesResourceDefaultVersion:
    Type: AWS::CloudFormation::ResourceDefaultVersion
    Properties:
      TypeVersionArn: !Ref KubernetesResourceVersion
